FROM golang:1.26-bookworm AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /kube-gpu-agent ./cmd/kube-gpu-agent/

FROM nvidia/cuda:12.9.0-base-ubuntu24.04

COPY --from=builder /kube-gpu-agent /usr/local/bin/kube-gpu-agent

ENTRYPOINT ["kube-gpu-agent"]
