// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gpuagent.proto

package gpuagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GPUStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUStatusRequest) Reset() {
	*x = GPUStatusRequest{}
	mi := &file_gpuagent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUStatusRequest) ProtoMessage() {}

func (x *GPUStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpuagent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUStatusRequest.ProtoReflect.Descriptor instead.
func (*GPUStatusRequest) Descriptor() ([]byte, []int) {
	return file_gpuagent_proto_rawDescGZIP(), []int{0}
}

type GPUStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Devices       []*GPUDevice           `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUStatusResponse) Reset() {
	*x = GPUStatusResponse{}
	mi := &file_gpuagent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUStatusResponse) ProtoMessage() {}

func (x *GPUStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpuagent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUStatusResponse.ProtoReflect.Descriptor instead.
func (*GPUStatusResponse) Descriptor() ([]byte, []int) {
	return file_gpuagent_proto_rawDescGZIP(), []int{1}
}

func (x *GPUStatusResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GPUStatusResponse) GetDevices() []*GPUDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GPUDevice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uuid  string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // e.g. "NVIDIA A100-SXM4-80GB"
	Index uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// Utilization
	GpuUtilization uint32 `protobuf:"varint,4,opt,name=gpu_utilization,json=gpuUtilization,proto3" json:"gpu_utilization,omitempty"` // 0-100%
	MemUtilization uint32 `protobuf:"varint,5,opt,name=mem_utilization,json=memUtilization,proto3" json:"mem_utilization,omitempty"` // 0-100%
	// Memory
	MemUsedBytes  uint64 `protobuf:"varint,6,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes uint64 `protobuf:"varint,7,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	// Thermal & Power
	TemperatureC    uint32 `protobuf:"varint,8,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	PowerWatts      uint32 `protobuf:"varint,9,opt,name=power_watts,json=powerWatts,proto3" json:"power_watts,omitempty"`
	PowerLimitWatts uint32 `protobuf:"varint,10,opt,name=power_limit_watts,json=powerLimitWatts,proto3" json:"power_limit_watts,omitempty"`
	// Pod attribution (empty if no pod is using this GPU)
	Pod           *PodInfo `protobuf:"bytes,11,opt,name=pod,proto3" json:"pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUDevice) Reset() {
	*x = GPUDevice{}
	mi := &file_gpuagent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUDevice) ProtoMessage() {}

func (x *GPUDevice) ProtoReflect() protoreflect.Message {
	mi := &file_gpuagent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUDevice.ProtoReflect.Descriptor instead.
func (*GPUDevice) Descriptor() ([]byte, []int) {
	return file_gpuagent_proto_rawDescGZIP(), []int{2}
}

func (x *GPUDevice) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUDevice) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUDevice) GetGpuUtilization() uint32 {
	if x != nil {
		return x.GpuUtilization
	}
	return 0
}

func (x *GPUDevice) GetMemUtilization() uint32 {
	if x != nil {
		return x.MemUtilization
	}
	return 0
}

func (x *GPUDevice) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *GPUDevice) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *GPUDevice) GetTemperatureC() uint32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *GPUDevice) GetPowerWatts() uint32 {
	if x != nil {
		return x.PowerWatts
	}
	return 0
}

func (x *GPUDevice) GetPowerLimitWatts() uint32 {
	if x != nil {
		return x.PowerLimitWatts
	}
	return 0
}

func (x *GPUDevice) GetPod() *PodInfo {
	if x != nil {
		return x.Pod
	}
	return nil
}

type PodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Container     string                 `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodInfo) Reset() {
	*x = PodInfo{}
	mi := &file_gpuagent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodInfo) ProtoMessage() {}

func (x *PodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gpuagent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodInfo.ProtoReflect.Descriptor instead.
func (*PodInfo) Descriptor() ([]byte, []int) {
	return file_gpuagent_proto_rawDescGZIP(), []int{3}
}

func (x *PodInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodInfo) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

var File_gpuagent_proto protoreflect.FileDescriptor

const file_gpuagent_proto_rawDesc = "" +
	"\n" +
	"\x0egpuagent.proto\x12\bgpuagent\"\x12\n" +
	"\x10GPUStatusRequest\"_\n" +
	"\x11GPUStatusResponse\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12-\n" +
	"\adevices\x18\x02 \x03(\v2\x13.gpuagent.GPUDeviceR\adevices\"\x80\x03\n" +
	"\tGPUDevice\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12'\n" +
	"\x0fgpu_utilization\x18\x04 \x01(\rR\x0egpuUtilization\x12'\n" +
	"\x0fmem_utilization\x18\x05 \x01(\rR\x0ememUtilization\x12$\n" +
	"\x0emem_used_bytes\x18\x06 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\a \x01(\x04R\rmemTotalBytes\x12#\n" +
	"\rtemperature_c\x18\b \x01(\rR\ftemperatureC\x12\x1f\n" +
	"\vpower_watts\x18\t \x01(\rR\n" +
	"powerWatts\x12*\n" +
	"\x11power_limit_watts\x18\n" +
	" \x01(\rR\x0fpowerLimitWatts\x12#\n" +
	"\x03pod\x18\v \x01(\v2\x11.gpuagent.PodInfoR\x03pod\"Y\n" +
	"\aPodInfo\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcontainer\x18\x03 \x01(\tR\tcontainer2Z\n" +
	"\x0fGPUAgentService\x12G\n" +
	"\fGetGPUStatus\x12\x1a.gpuagent.GPUStatusRequest\x1a\x1b.gpuagent.GPUStatusResponseB.Z,github.com/jia-gao/kube-gpu-top/api/gpuagentb\x06proto3"

var (
	file_gpuagent_proto_rawDescOnce sync.Once
	file_gpuagent_proto_rawDescData []byte
)

func file_gpuagent_proto_rawDescGZIP() []byte {
	file_gpuagent_proto_rawDescOnce.Do(func() {
		file_gpuagent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gpuagent_proto_rawDesc), len(file_gpuagent_proto_rawDesc)))
	})
	return file_gpuagent_proto_rawDescData
}

var file_gpuagent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gpuagent_proto_goTypes = []any{
	(*GPUStatusRequest)(nil),  // 0: gpuagent.GPUStatusRequest
	(*GPUStatusResponse)(nil), // 1: gpuagent.GPUStatusResponse
	(*GPUDevice)(nil),         // 2: gpuagent.GPUDevice
	(*PodInfo)(nil),           // 3: gpuagent.PodInfo
}
var file_gpuagent_proto_depIdxs = []int32{
	2, // 0: gpuagent.GPUStatusResponse.devices:type_name -> gpuagent.GPUDevice
	3, // 1: gpuagent.GPUDevice.pod:type_name -> gpuagent.PodInfo
	0, // 2: gpuagent.GPUAgentService.GetGPUStatus:input_type -> gpuagent.GPUStatusRequest
	1, // 3: gpuagent.GPUAgentService.GetGPUStatus:output_type -> gpuagent.GPUStatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gpuagent_proto_init() }
func file_gpuagent_proto_init() {
	if File_gpuagent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gpuagent_proto_rawDesc), len(file_gpuagent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpuagent_proto_goTypes,
		DependencyIndexes: file_gpuagent_proto_depIdxs,
		MessageInfos:      file_gpuagent_proto_msgTypes,
	}.Build()
	File_gpuagent_proto = out.File
	file_gpuagent_proto_goTypes = nil
	file_gpuagent_proto_depIdxs = nil
}
