// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: gpuagent.proto

package gpuagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GPUAgentService_GetGPUStatus_FullMethodName = "/gpuagent.GPUAgentService/GetGPUStatus"
)

// GPUAgentServiceClient is the client API for GPUAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GPUAgentServiceClient interface {
	GetGPUStatus(ctx context.Context, in *GPUStatusRequest, opts ...grpc.CallOption) (*GPUStatusResponse, error)
}

type gPUAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUAgentServiceClient(cc grpc.ClientConnInterface) GPUAgentServiceClient {
	return &gPUAgentServiceClient{cc}
}

func (c *gPUAgentServiceClient) GetGPUStatus(ctx context.Context, in *GPUStatusRequest, opts ...grpc.CallOption) (*GPUStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GPUStatusResponse)
	err := c.cc.Invoke(ctx, GPUAgentService_GetGPUStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPUAgentServiceServer is the server API for GPUAgentService service.
// All implementations must embed UnimplementedGPUAgentServiceServer
// for forward compatibility.
type GPUAgentServiceServer interface {
	GetGPUStatus(context.Context, *GPUStatusRequest) (*GPUStatusResponse, error)
	mustEmbedUnimplementedGPUAgentServiceServer()
}

// UnimplementedGPUAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGPUAgentServiceServer struct{}

func (UnimplementedGPUAgentServiceServer) GetGPUStatus(context.Context, *GPUStatusRequest) (*GPUStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPUStatus not implemented")
}
func (UnimplementedGPUAgentServiceServer) mustEmbedUnimplementedGPUAgentServiceServer() {}
func (UnimplementedGPUAgentServiceServer) testEmbeddedByValue()                         {}

// UnsafeGPUAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUAgentServiceServer will
// result in compilation errors.
type UnsafeGPUAgentServiceServer interface {
	mustEmbedUnimplementedGPUAgentServiceServer()
}

func RegisterGPUAgentServiceServer(s grpc.ServiceRegistrar, srv GPUAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedGPUAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GPUAgentService_ServiceDesc, srv)
}

func _GPUAgentService_GetGPUStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GPUStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUAgentServiceServer).GetGPUStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUAgentService_GetGPUStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUAgentServiceServer).GetGPUStatus(ctx, req.(*GPUStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPUAgentService_ServiceDesc is the grpc.ServiceDesc for GPUAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpuagent.GPUAgentService",
	HandlerType: (*GPUAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGPUStatus",
			Handler:    _GPUAgentService_GetGPUStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpuagent.proto",
}
